In [2]:
import math
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from sklearn.datasets import load_iris


import torch
import torch.nn.functional as F

iris= load_iris()
data = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['target'])

In [3]:
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [4]:
print(data)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0       0.0  

In [5]:
x = data.iloc[:, :-1]

y = data['target']   

In [6]:
#.tolist()
x.iloc[0].tolist()

[5.1, 3.5, 1.4, 0.2]

In [7]:
y[0]

0.0

In [8]:
# custom dataset 
class CustomDataset(torch.utils.data.Dataset):
    def __init__(self, df):

        self.x_data = df.iloc[:, :-1] # x data dataframe으로 
        self.y_data = df['target'] # y data target
   
    #총 데이터 개수를 리턴
    def __len__(self):
        return len(self.x_data)

    #인덱스를 입력받아 그에 맵핑되는 입출력 데이터를 Pytorch Tensor 형태로 전환
    def __getitem__(self, idx):
        
        x = self.x_data.iloc[idx].tolist()
        x = torch.tensor(x)
        y = self.y_data[idx]
        
        y = torch.tensor(y)
        
        return x, y

In [9]:
dataset = CustomDataset(data)
dataloadeer = DataLoader(dataset, batch_size = 2, shuffle = True)

In [11]:
import torch
import torchvision.transforms as transforms

# data를 분리해서 클래스 ( )안에 넣는다면?


# x_train, x_valid, y_train, y_valid = train
split_ratio = 0.7
split_index = int(split_ratio * len(data))

# train shuffle test not shuffle

train_dataset = CustomDataset(data[ : split_index ])
test_dataset = CustomDataset(data[split_index : ])

dataLoader = torch.utils.data.DataLoader(dataset, batch_size=1, shuffle=True)

dataiter = iter(dataLoader)

feature, target = dataiter.next() # 값 확인하는 용으로 data 잘 들어가는 가 batch 마다

print(feature)
print(target)

tensor([[5.8000, 2.8000, 5.1000, 2.4000]])
tensor([2.], dtype=torch.float64)


In [12]:
split_ratio = 0.7
split_index = int(split_ratio * len(data))

train_dataset = CustomDataset(data[: split_index ])
test_dataset = CustomDataset(data[split_index : ]) 

train_dataLoader = torch.utils.data.DataLoader(train_dataset, batch_size=1, shuffle=True)
test_dataLoader = torch.utils.data.DataLoader(test_dataset, batch_size=1, shuffle=True)


In [13]:
len(train_dataset), len(test_dataset)

(105, 45)

In [14]:
dataiter = iter(dataLoader)

feature, target = dataiter.next() # 값 확인하는 용으로 data 잘 들어가는 가 batch 마다

print(feature)
print(target)

tensor([[6.4000, 2.9000, 4.3000, 1.3000]])
tensor([1.], dtype=torch.float64)
